name: "Ruby on Rails CI"
on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
jobs:
  test:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:16-alpine
        ports:
          - "5432:5432"
        env:
          POSTGRES_DB: rails_test_test
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: DifficultPassword
    env:
      RAILS_ENV: test
      DATABASE_URL: "postgres://postgres:DifficultPassword@localhost:5432/rails_test_test"
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      # Add or replace dependency steps here
      - name: Install Ruby and gems
        uses: ruby/setup-ruby@55283cc23133118229fd3f97f9336ee23a179fcf # v1.146.0
        with:
          bundler-cache: true
          ruby-version: 3.2.2
      # Add or replace database setup steps here
      # - name: Set up database schema
      #   run: bin/rails db:schema:load
      # Add or replace test runners here
      - name: Run tests
        run: bundle exec rspec

  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Install Ruby and gems
        uses: ruby/setup-ruby@55283cc23133118229fd3f97f9336ee23a179fcf # v1.146.0
        with:
          bundler-cache: true
          ruby-version: 3.2.2
      # Add or replace any other lints here
      - name: Lint Ruby files
        run: bundle exec rubocop --parallel
